### ISSUE TITLE
Release erstellen

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/uppy#4]
Erstes Release erstellen und im Installer veröffentlichen.
Danach das 🐣 Küken aus der AddOn-Beschreibung entfernen. :)

**Comment by skerbis** [comment]
@schuer hier steckt noch Arbeit drin. Wir kommen nur nicht dazu

**Comment by schuer** [comment]
@skerbis Kein Stress! Ist nur ein Reminder, damit es nicht vergessen wird.

**Comment by schuer** [comment]
Whatever :)

**Comment by skerbis** [comment]
@schuer das wollten andere übernehmen, ich bin hier raus

**Comment by schuer** [comment]
@skerbis Sollte keine Kritik sein und war auch nicht an dich gerichtet. Ich räume nur alte Issues weg, und bei Uppy besteht seit 2019 offenbar keinerlei Bedarf an einem Release.
