### ISSUE TITLE
CSRF Token invalid (im Frontend)

### ISSUE THREAD

**Issue by MC-PMOE** [FriendsOfREDAXO/uppy#6]
`UppyTokenProvider::isTokenValid()`
scheint bei der Benutzung im Frontend nicht das gewünschte Ergebnis zu liefern, nach dem auskommentieren der entsprechenden Zeile lief das Skript ohne Probleme. Weitere Infos kann ich gerne nachreichen

**Comment by skerbis** [comment]
sollte jetzt funktionieren. Der Key war falsch
